---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(\"dashboard.example.com\") && (PathPrefix(\"/api\") || PathPrefix(\"/dashboard\"))
      services:
        - kind: Service
          name: traefik
          port: 9000
